//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseEntities : DbContext
    {
        public DataBaseEntities()
            : base("name=DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Аудитории> Аудитории { get; set; }
        public virtual DbSet<Группы> Группы { get; set; }
        public virtual DbSet<Дисциплины> Дисциплины { get; set; }
        public virtual DbSet<Журнал> Журнал { get; set; }
        public virtual DbSet<Занятие> Занятие { get; set; }
        public virtual DbSet<Кафедры> Кафедры { get; set; }
        public virtual DbSet<Преподаватели> Преподаватели { get; set; }
        public virtual DbSet<Расписание> Расписание { get; set; }
        public virtual DbSet<Регистрация> Регистрация { get; set; }
        public virtual DbSet<Специальности> Специальности { get; set; }
        public virtual DbSet<Учащиеся> Учащиеся { get; set; }
        public virtual DbSet<Факультет> Факультет { get; set; }
    }
}
