//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Журнал
    {
        public Nullable<int> ID_Учащегося { get; set; }
        public Nullable<int> ID_дисциплины { get; set; }
        public Nullable<int> ID_преподавателя { get; set; }
        public System.DateTime Дата { get; set; }
        public int Оценки { get; set; }
        public string Пропуски { get; set; }
        public int ID_журнала { get; set; }
    
        public virtual Дисциплины Дисциплины { get; set; }
        public virtual Преподаватели Преподаватели { get; set; }
        public virtual Учащиеся Учащиеся { get; set; }
    }
}
