//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Занятие
    {
        public int ID_Занятия { get; set; }
        public int C_ID_Расписания { get; set; }
        public int Неделя { get; set; }
        public int ID_Дисциплины { get; set; }
        public int ID_Группы { get; set; }
        public System.DateTime ДатаИВремя { get; set; }
        public Nullable<int> ID_Аудитории { get; set; }
    
        public virtual Аудитории Аудитории { get; set; }
        public virtual Группы Группы { get; set; }
        public virtual Дисциплины Дисциплины { get; set; }
        public virtual Расписание Расписание { get; set; }
    }
}
