//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Преподаватели
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Преподаватели()
        {
            this.Дисциплины = new HashSet<Дисциплины>();
            this.Журнал = new HashSet<Журнал>();
            this.Расписание = new HashSet<Расписание>();
        }
    
        public int ID_преподавателя { get; set; }
        public string Фамилия_преподавателя { get; set; }
        public string Имя_преподавателя { get; set; }
        public string Отчество_преподавателя { get; set; }
        public Nullable<int> Пол { get; set; }
        public string Код_кафедры { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Дисциплины> Дисциплины { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Журнал> Журнал { get; set; }
        public virtual Кафедры Кафедры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Расписание> Расписание { get; set; }
    }
}
