//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Расписание()
        {
            this.Занятие = new HashSet<Занятие>();
        }
    
        public int ID_Расписания { get; set; }
        public int ID_Преподавателя { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Занятие> Занятие { get; set; }
        public virtual Преподаватели Преподаватели { get; set; }
    }
}
