//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Регистрация
    {
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<int> Роли { get; set; }
        public Nullable<int> Ид_пользователя { get; set; }
        public int ID_регистрации { get; set; }
    }
}
