//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Учащиеся
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Учащиеся()
        {
            this.Журнал = new HashSet<Журнал>();
        }
    
        public int ID_Учащегося { get; set; }
        public string Фамилия_Учащегося { get; set; }
        public string Имя_Учащегося { get; set; }
        public string Отчество_Учащегося { get; set; }
        public Nullable<int> ID_группы { get; set; }
        public string Дополнительная_информация { get; set; }
        public Nullable<int> Пол { get; set; }
    
        public virtual Группы Группы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Журнал> Журнал { get; set; }
    }
}
